### ISSUE TITLE
[TODO] Prepare for the v1.0.1 release

### ISSUE THREAD

**Issue by jakecastelli** [jakecastelli/trongate-vscode#11]
# Packing

- [x] Pack it with webpack - reduce the extension size massively @jakecastelli 

# Heavy Testing 

- [x] Window @DaFa66 

- [x] MacOS @jakecastelli 

- [x] Ubuntu  @jakecastelli 

- [x] Gif, ReadMe @DaFa66 @jakecastelli

**Comment by DaFa66** [comment]
I'll be adding to the video and putting it up on YouTube a bit later tonight when I get some time 👍

**Comment by jakecastelli** [comment]
v1.0.1 has been released!

**Comment by DaFa66** [comment]
Fantastic! 😊
