### ISSUE TITLE
Can't Install the extension

### ISSUE THREAD

**Issue by andymlr** [jakecastelli/trongate-vscode#2]
When trying to install this extension i get this error message.
I'm on a Mac btw if that makes a difference.

"Unable to install 'jc-sf.trongate' extension because it is not compatible with the current version of VS Code (version 1.48.2)."

**Comment by andymlr** [comment]
Nevermind, i thought by updating VS Code once it would update straight to the newest version. Turns out i had to update the app a couple times.

**Comment by jakecastelli** [comment]
Thanks for reporting this issue Andy.

I guess I will need to make it compatible to lower versions as well in the next release.

**Comment by jakecastelli** [comment]
Hi Andy,

Just a quick update in terms of the issue.
I really do appreciate your previous feedback to let us know the compatibility issue with lower version VSCode, this is something Simon and I haven't thought about before and it may truly destroy the user experience as some of the users do not constantly use or update their VSCode.

Simon and I have lowered the Trongate VSCode Extension requirement to compatible with VSCode 1.31.0 (which is a quick old version from Nov 2018). Hopefully this would help the later users.

Please do let us know your thoughts, we would like to constantly improve the extension!

Cheers,
Jake
