### ISSUE TITLE
Typos in the generated view_file.(my hacktober donation) hehe

### ISSUE THREAD

**Issue by monxian** [jakecastelli/trongate-vscode#20]
`<?php
class Test extends Trongate {
   
    function index () {
        $data['view_module'] = 'test';
        $this->view('test_view', $data);
        /* Uncomment the lines below, 
         * Change the template method name, 
         * Remove lines above, if you want to load to the template
         */
        //$data['view_module'] = 'test';
        //$ data['view_file] = 'test_view';
        //$this->template('template method here', $data);
    }  
}`

In the commented out line the view file one. $data has a space $ data and the brackets need a closing  apostrophe.

**Comment by jakecastelli** [comment]
Well spotted mate!

We have fixed that problem in our dev branch, this typo along with few others will not be appearing in the next release.

Cheers Bobby
