### ISSUE TITLE
Add Trongate CSS to nitro

### ISSUE THREAD

**Issue by jakecastelli** [jakecastelli/trongate-vscode#40]

**Comment by jakecastelli** [comment]
Hi mate, how's going with adding Trongate CSS?

**Comment by DaFa66** [comment]
Hi Jake,
Been caught up with work lately, just submitted a big tender.  Will try get
some more done soon.

**Comment by jakecastelli** [comment]
All good mate, no stress!

Let me know if anything I can help with, talk soon!

**Comment by DaFa66** [comment]
Hi Jake,

Hope all is well with you and the family.  Not sure if you have had a look at the Trongate-CSS branch I've got started on.  Maybe give me a call and we can jump on a Skype call to discuss and finish it off.

Cheers,
Simon
