### ISSUE TITLE
Set default file as a php file

### ISSUE THREAD

**Issue by Andrewsuares** [jakecastelli/trongate-vscode#5]
Excellent extension.

For those wondering how to set a new file to php by default.

Files > Preferences > Settings
Files: Default Language

Enter php in the box.

**Comment by jakecastelli** [comment]
Hi Andrew,

Thank you for your suggestion, may I ask under which circumstance you need to set a new file to php by default?

Cheers, 
Jake

**Comment by Andrewsuares** [comment]
I use Vscode to work on php files. And so the default to php is fast for me without having to change anything.

**Comment by Andrewsuares** [comment]
Hi Jake,

Any ideas to allow users to submit code snippets. 1) A method to add code extensions directly to the Vscode extension. This would be local to the user and 2) A method to add to the snippets that makes it available to everyone. I'm thinking maybe something like ublock origin, the extension that blocks ads. Filters are auto-updated and downloaded to the browser. Your extension in Vscode could do the same.

**Comment by jakecastelli** [comment]
Hi Andrew, you can [create your own snippets directly by using VSCode](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets) either locally or globally within VSCode.

The Trongate VSCode extension intends to keep the amount of snippets to the bare minimal as every user has its own preference.
If you think there are some good snippets you can always suggest inside the sca forum, if many of us agreed upon it, then we would pack it into the next lease.

Cheers.

**Comment by DaFa66** [comment]
Another option would be to fork the repo, add your snippet and do a push
request for Jake and myself to review for inclusion in the next release.
